### ISSUE TITLE
Options page broken

### ISSUE THREAD

**Issue by SupDos** [animekkk/twitch-enhancer#11]
On Firefox, when pressing the extension button or going to options in about:addons the options page throws an error:

![image](https://user-images.githubusercontent.com/6813986/151680008-48e28d7d-11e9-48ac-8522-1b8d9427fe78.png)

**Comment by animekkk** [comment]
fixed in a8f14133f48f6500c1f1aa219bbf9b7046438e16

currently you can manually remove one pages from url, but it new version should be up very soon
