### ISSUE TITLE
Safari

### ISSUE THREAD

**Issue by ayechief** [animekkk/twitch-enhancer#17]
Hey, 
could you, please, add Safari macOS? I use BTTV in safari as js script loaded with GreaseMonkey or something and it can work that way here but for BTTV I have just a single js file. 

using m1 Mac /pl

**Comment by ayechief** [comment]
alternative for making single js file is adding extension to Mac app store, so it can be easily downloaded do safari

**Comment by animekkk** [comment]
Sorry, but for now Safari will still not be supported.
