### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by MyNameIsTito** [animekkk/twitch-enhancer#22]
Not personally annoyed at it but I believe it would be nicer saying "them" instead of identifying a sex on the user. I believe the user is a female also.

Besides that f*cking great extension BroBalt

![image](https://user-images.githubusercontent.com/46318667/167057077-ac0287ca-1b37-4577-8b8a-eb5bc96068e1.png)

**Comment by animekkk** [comment]
changed in e1959927ec27c9b0bb6f381a30469810eefbf6e3
