### ISSUE TITLE
Feature Request: Add vislaud.com/[streamer name] to Quick access links

### ISSUE THREAD

**Issue by Velegand** [animekkk/twitch-enhancer#3]
![image](https://user-images.githubusercontent.com/69394829/148778612-e562744f-12ec-4d54-ad15-a061410aa10c.png)
xayo.pl doesn't work for any of the streamers that I watch because I watch English streamers.

**Comment by animekkk** [comment]
thanks for reporting this i completely forgot to add this
906bffba5a3def58e1d2d974379f5a57c8f1de89
