### ISSUE TITLE
New number next to Viewer Count

### ISSUE THREAD

**Issue by SupDos** [animekkk/twitch-enhancer#43]
Heya, recently saw a new number was added next to the viewer count, but I can't seem to figure out what it means
![image](https://user-images.githubusercontent.com/6813986/191330634-616995f3-c052-484c-83ac-2b9146de086b.png)
clicking it doesn't do anything, and I've gone through a bit of the commit history but I still can't figure it out
nothing about it in settings either, can it not be disabled?

Sorry if this is a really stupid question Pepega

**Comment by animekkk** [comment]
It is chatters count.
I forgot to add tooltip, but it will be added tomorrow.
846088360b419a9250253dd2fec2075f807974ea
